name: "[New] feature request"
description: "Reports regarding bug, slow performance, memory issues, installation issues"

title: "[New] "
labels: ["enhancement", "brainstorming", "documentation"]

body:
  - type: markdown
    attributes:
      value: Always welcome, CovsirPhy project is developed by a community of volunteers :)

  - type: checkboxes
    id: consent
    attributes:
      label: Checkbox
      options:
        - label: I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
          required: true
        - label: I have confirmed I used [the latest version of covsirphy](https://lisphilar.github.io/covid19-sir/markdown/INSTALLATION.html).
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Please provide the summary.
    validations:
      required: true

  - type: textarea
    id: solutions
    attributes:
      label: Solutions
      placeholder: Solutions, if available.

  - type: textarea
    id: deprecations
    attributes:
      label: APIs to be deprecated
      placeholder: APIs to be deprecated, if the new feature replaces their functionalities.

  - type: textarea
    id: comment
    attributes:
      label: Additional Context
      placeholder: Additional Context to fix the bug, including useful references.
