name: "[Dev] revise development workflow"
description: "This may update ./.github directory, ./Makefile, ./pyproject.toml etc."

title: "[Dev] "
labels: ["development", "brainstorming"]

body:
  - type: markdown
    attributes:
      value: Always welcome, CovsirPhy project is developed by a community of volunteers :)

  - type: checkboxes
    id: consent
    attributes:
      label: Checkbox
      options:
        - label: I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
          required: true
        - label: I have confirmed I will follow and update [contribution guideline](https://lisphilar.github.io/covid19-sir/CONTRIBUTING.html).
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Issues of the current workflow
      placeholder: What is the problem?
    validations:
      required: true

  - type: textarea
    id: action
    attributes:
      label: Action items
      placeholder: Action items to solve this issue.

  - type: textarea
    id: comment
    attributes:
      label: Additional Context
      placeholder: Additional Context to fix the bug, including useful references.
