name: "[Docs] improve documentation"
description: "Improve documentation, README and https://lisphilar.github.io/covid19-sir/"

title: "[Docs] "
labels: ["documentation", "good first issue"]

body:
  - type: markdown
    attributes:
      value: Always welcome, CovsirPhy project is developed by a community of volunteers :)

  - type: checkboxes
    id: consent
    attributes:
      label: Checkbox
      options:
        - label: I agree to follow [code of conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
          required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested improvement of documentation
      placeholder: What is the issue?
    validations:
      required: true
